name: deepl_dart
description: Dart library for the DeepL language translation API. Pure Dart. Inspired by the official DeepL API documentation.
version: 2.0.0
homepage: https://github.com/komape/deepl_dart
repository: https://github.com/komape/deepl_dart
issue_tracker: https://github.com/komape/deepl_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http: ^1.1.0
  json_annotation: ^4.9.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.9.4
  lints: ^4.0.0
  test: ^1.24.4
