name: deepl_dart
description: Dart library for the DeepL language translation API.
version: 1.3.0
homepage: https://github.com/komape/deepl_dart
repository: https://github.com/komape/deepl_dart
issue_tracker: https://github.com/komape/deepl_dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.4
